### ISSUE TITLE
keycloak 11.0.2

### ISSUE THREAD

**Issue by morexlt** [dasniko/keycloak-user-spi-demo#5] opened 2020-09-14 16:41 UTC
Hey! have you test on keycloak 11.0.2? 
i have a custom implementation of this example, and when i update to Keycloak 11.0.2 the User Detail is not getting any attribute. Then i tested with your example and it dont work neither.
Can you help me pls? 

Thanks!

**Comment by dasniko** [comment] 2020-09-14 17:35
Might be in conjunction to https://www.keycloak.org/docs/latest/upgrading/index.html#usermodel-changes ?

**Comment by morexlt** [comment] 2020-09-14 19:10
Yes I read it, but right there it says:
`The public API of **UserModel** has not changed, so no changes to frontend resources or SPIs accessing user data should be necessary. The database has also not changed, yet.
`
In fact, when I search for users, in the list they appear with the attributes, but when I go to the detail of any user, it only show me the username, and the others attributes in blank. I add some log on the getXXX() methods but no one are called when i go to detail, so i dont know where is the problem/change.
I know it's not a problem with your example, i just asking for help, because this example brought me much more help than the doc in keycloak page.

**Comment by dasniko** [comment] 2020-09-14 19:25
Currently I don‘t have time to investigate further, sorry. You‘ll have to two weeks or so.

I‘m pretty sure that it is related to the change mentioned. Public API didn‘t change, yes, but it may depend on custom implementation and possibly class casting.

**Comment by Martin-Idel-SI** [comment] 2020-09-24 13:40
The problem is the following: Your `UserAdapter` inherits from `AbstractUserAdapterFederatedStorage` here:

https://github.com/dasniko/keycloak-user-spi-demo/blob/ac06b80f6bcb0a95837b2723ba788251fb4de7e3/src/main/java/dasniko/keycoak/user/UserAdapter.java#L12

However, this adapter has an assumption that you only modify the getUsername/setUsername (abstract) methods and leave other methods in tact:

https://github.com/keycloak/keycloak/blob/5d5e56dde3bc841c7d1d0261cfcaf372cdf119bc/server-spi/src/main/java/org/keycloak/storage/adapter/AbstractUserAdapterFederatedStorage.java#L41

This assumption is violated in the implementation of this PR, which leads to the observed behaviour. The functions `getEmail` etc. had to change - and these changes must be reflected in your UserAdapter.

We discussed the issue during the original PR (see especially https://github.com/keycloak/keycloak/pull/7080#discussion_r439461477) and it was explicitly assumed that subclassing `AbstractUserAdapterFederatedStorage` and the answer was that this is the way things should change and the case we see here should not happen. I was in favour of breaking at compile time, so you could have caught this easier.

The message in the upgrade guide really only referred to SPIs accessing user data (i.e. calling `UserModel` functions) - this SPI changes the way how user data is stored, which is entirely different.

So yes: This SPI needs to change.  Sorry for the inconvenience!

**Comment by dasniko** [comment] 2020-09-24 13:57
Thanks @Martin-Idel-SI 

I noticed similar behavior in the last week at a customer of mine. A compile time error would have made things easier to detect, but anyhow, I solved it and will fix this demo SPI soon.

**Comment by dasniko** [comment] 2020-09-24 21:34
It's fixed now and this demo user spi is working again with current KC version.

Thanks for reporting.

**Closed as completed by dasniko** 2020-09-24 21:34 UTC
